/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : DirecaoEsquerdaOut.c
**     Project   : Lab3Questao3
**     Processor : MC9S12C128CFU16
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.16, CPU db: 2.87.411
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 09/03/2021, 16:22
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       21            |  PB5_ADDR5_DATA5
**             ----------------------------------------------------
**
**         Port name                   : B
**
**         Bit number (in port)        : 5
**         Bit mask of the port        : $0020
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PORTB     [$0001]
**         Port control register       : DDRB      [$0003]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool DirecaoEsquerdaOut_GetVal(void);
**         PutVal - void DirecaoEsquerdaOut_PutVal(bool Val);
**         ClrVal - void DirecaoEsquerdaOut_ClrVal(void);
**         SetVal - void DirecaoEsquerdaOut_SetVal(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE DirecaoEsquerdaOut. */

#include "DirecaoEsquerdaOut.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG DirecaoEsquerdaOut_DATA /* Select data segment "DirecaoEsquerdaOut_DATA" */
#pragma CODE_SEG DirecaoEsquerdaOut_CODE
#pragma CONST_SEG DirecaoEsquerdaOut_CONST /* Constant section for this module */
/*
** ===================================================================
**     Method      :  DirecaoEsquerdaOut_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
/*
bool DirecaoEsquerdaOut_GetVal(void)

**  This method is implemented as a macro. See DirecaoEsquerdaOut.h file.  **
*/

/*
** ===================================================================
**     Method      :  DirecaoEsquerdaOut_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void DirecaoEsquerdaOut_PutVal(bool Val)
{
  if (Val) {
    setReg8Bits(PORTB, 0x20U);         /* BIT5=0x01U */
  } else { /* !Val */
    clrReg8Bits(PORTB, 0x20U);         /* BIT5=0x00U */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  DirecaoEsquerdaOut_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void DirecaoEsquerdaOut_ClrVal(void)

**  This method is implemented as a macro. See DirecaoEsquerdaOut.h file.  **
*/

/*
** ===================================================================
**     Method      :  DirecaoEsquerdaOut_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void DirecaoEsquerdaOut_SetVal(void)

**  This method is implemented as a macro. See DirecaoEsquerdaOut.h file.  **
*/


/* END DirecaoEsquerdaOut. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
