/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : VelocidadeParaBrisa.h
**     Project   : Lab3Questao3
**     Processor : MC9S12C128CFU16
**     Component : PWM
**     Version   : Component 02.231, Driver 01.16, CPU db: 2.87.411
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 09/03/2021, 17:31
**     Abstract  :
**         This component implements a pulse-width modulation generator
**         that generates signal with variable duty and fixed cycle. 
**     Settings  :
**         Used output pin             : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       2             |  PP2_PWM2_KWP2
**             ----------------------------------------------------
**
**         Timer name                  : PWM2 [8-bit]
**         Counter                     : PWMCNT2   [$00EE]
**         Mode register               : PWMCTL    [$00E5]
**         Run register                : PWME      [$00E0]
**         Prescaler                   : PWMPRCLK  [$00E3]
**         Compare 1 register          : PWMPER2   [$00F4]
**         Compare 2 register          : PWMDTY2   [$00FA]
**         Flip-flop 1 register        : PWMPOL    [$00E1]
**
**         User handling procedure     : not specified
**
**         Output pin
**
**         Port name                   : P
**         Bit number (in port)        : 2
**         Bit mask of the port        : $0004
**         Port data register          : PTP       [$0258]
**         Port control register       : DDRP      [$025A]
**
**         Runtime setting period      : none
**         Runtime setting ratio       : calculated
**         Initialization:
**              Aligned                : Left
**              Output level           : low
**              Timer                  : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 267 Hz
**           Initial value of            period        pulse width (ratio 10.58%)
**             Xtal ticks              : 15275520      1617408
**             microseconds            : 954720        101088
**             milliseconds            : 955           101
**             seconds                 : 1             0
**             seconds (real)          : 0.95472       0.101088
**
**     Contents  :
**         Enable         - byte VelocidadeParaBrisa_Enable(void);
**         Disable        - byte VelocidadeParaBrisa_Disable(void);
**         SetRatio8      - byte VelocidadeParaBrisa_SetRatio8(byte Ratio);
**         SetRatio16     - byte VelocidadeParaBrisa_SetRatio16(word Ratio);
**         SetDutyTicks16 - byte VelocidadeParaBrisa_SetDutyTicks16(word Ticks);
**         SetDutyTicks32 - byte VelocidadeParaBrisa_SetDutyTicks32(dword Ticks);
**         SetDutyUS      - byte VelocidadeParaBrisa_SetDutyUS(word Time);
**         SetDutyMS      - byte VelocidadeParaBrisa_SetDutyMS(word Time);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __VelocidadeParaBrisa
#define __VelocidadeParaBrisa

/* MODULE VelocidadeParaBrisa. */

#include "Cpu.h"

#pragma CODE_SEG VelocidadeParaBrisa_CODE

#define VelocidadeParaBrisa_PERIOD_VALUE 0xFFUL /* Initial period value in ticks of the timer */
#define VelocidadeParaBrisa_PERIOD_VALUE_HIGH 0xFFUL /* Initial period value in ticks of the timer in high speed mode */

byte VelocidadeParaBrisa_Enable(void);
/*
** ===================================================================
**     Method      :  VelocidadeParaBrisa_Enable (component PWM)
**
**     Description :
**         This method enables the component - it starts the signal
**         generation. Events may be generated (<DisableEvent>
**         /<EnableEvent>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte VelocidadeParaBrisa_Disable(void);
/*
** ===================================================================
**     Method      :  VelocidadeParaBrisa_Disable (component PWM)
**
**     Description :
**         This method disables the component - it stops the signal
**         generation and events calling. When the timer is disabled,
**         it is possible to call <ClrValue> and <SetValue> methods.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte VelocidadeParaBrisa_SetRatio8(byte Ratio);
/*
** ===================================================================
**     Method      :  VelocidadeParaBrisa_SetRatio8 (component PWM)
**
**     Description :
**         This method sets a new duty-cycle ratio. The ratio is
**         expressed as an 8-bit unsigned integer number. Value 0 - 255
**         is proportional to ratio 0 - 100%. 
**         Note: Calculated duty depends on the timer possibilities and
**         on the selected period.
**         The method is available only if method <SetPeriodMode> is
**         not selected.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Ratio           - Ratio to set. 0 - 255 value is
**                           proportional to ratio 0 - 100%
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte VelocidadeParaBrisa_SetRatio16(word Ratio);
/*
** ===================================================================
**     Method      :  VelocidadeParaBrisa_SetRatio16 (component PWM)
**
**     Description :
**         This method sets a new duty-cycle ratio. Ratio is expressed
**         as a 16-bit unsigned integer number. Value 0 - 65535 value
**         is proportional to ratio 0 - 100%. 
**         Note: Calculated duty depends on the timer possibilities and
**         on the selected period.
**         The method is available only if method <SetPeriodMode> is
**         not selected.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Ratio           - Ratio to set. 0 - 65535 value is
**                           proportional to ratio 0 - 100%
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/

byte VelocidadeParaBrisa_SetDutyTicks16(word Ticks);
/*
** ===================================================================
**     Method      :  VelocidadeParaBrisa_SetDutyTicks16 (component PWM)
**
**     Description :
**         This method sets the new duty value of the output signal.
**         The duty is expressed in main oscillator (usualy External
**         osc., internal osc. if exits and external osc. is disabled)
**         ticks as a 16-bit unsigned integer number.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Ticks           - Duty to set in main oscillator ticks
**                      (0 to 65535 ticks in high speed mode)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/

byte VelocidadeParaBrisa_SetDutyTicks32(dword Ticks);
/*
** ===================================================================
**     Method      :  VelocidadeParaBrisa_SetDutyTicks32 (component PWM)
**
**     Description :
**         This method sets the new duty value of the output signal.
**         The duty is expressed in main oscillator (usually External
**         osc., internal osc. if exits and external osc. is disabled)
**         ticks as a 32-bit unsigned integer number.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Ticks           - Duty to set in Xtal ticks
**                      (0 to 15275520 ticks in high speed mode)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/

byte VelocidadeParaBrisa_SetDutyUS(word Time);
/*
** ===================================================================
**     Method      :  VelocidadeParaBrisa_SetDutyUS (component PWM)
**
**     Description :
**         This method sets the new duty value of the output signal. The
**         duty is expressed in microseconds as a 16-bit unsigned integer
**         number.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Time       - Duty to set [in microseconds]
**                      (0 to 65535 us in high speed mode)
**     Returns     :
**         ---        - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/

byte VelocidadeParaBrisa_SetDutyMS(word Time);
/*
** ===================================================================
**     Method      :  VelocidadeParaBrisa_SetDutyMS (component PWM)
**
**     Description :
**         This method sets the new duty value of the output signal. The
**         duty is expressed in milliseconds as a 16-bit unsigned integer
**         number.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Time       - Duty to set [in milliseconds]
**                      (0 to 955 ms in high speed mode)
**     Returns     :
**         ---        - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/

void VelocidadeParaBrisa_Init(void);
/*
** ===================================================================
**     Method      :  VelocidadeParaBrisa_Init (component PWM)
**
**     Description :
**         Initializes the associated peripheral(s) and the component's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma CODE_SEG DEFAULT

/* END VelocidadeParaBrisa. */

#endif /* ifndef __VelocidadeParaBrisa */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
